project:
  type: website
  output-dir: docs 

website:
  title: "BaileyStender.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Resume.qmd
        text: Resume
      - href: Projects.qmd
        text: Projects
    right:
      - href: https://github.com/BaileyStender
        text: GitHub
  

format:
  html:
    theme: styles.scss
    mainfont: Nunito
    toc: true

editor: visual

